conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

In [1]:
import torch
print(torch.__version__)

2.2.1


In [2]:
scalar = torch.tensor(7)
scalar
scalar.item()

7

In [3]:
vector = torch.tensor([3,4])
vector
vector.ndim
vector.shape

torch.Size([2])

In [4]:
matrix = torch.tensor([[3,4],[5,6]])
matrix
matrix.shape
matrix[1]

tensor([5, 6])

In [5]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]]])
tensor
# tensor.ndim
# tensor.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 2, 1],
         [6, 5, 4],
         [9, 8, 7]]])

In [6]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1717, 0.4134, 0.3579, 0.3545],
        [0.1033, 0.9346, 0.6262, 0.6711],
        [0.7745, 0.9596, 0.6323, 0.4695]])

In [7]:
random_image_size_tensor = torch.rand(size=(3, 224, 224,))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [8]:
zero = torch.zeros(3,4)
zero
zero.dtype

torch.float32

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.arange(0,10,2)
torch.zeros_like(input=torch.arange(1,11))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors datatype

1) Tensors not right datatype
2) Tensors not right shape
3) Tensors not the right device


In [11]:
float_32_tensor = torch.tensor([2.,3.0,4],dtype=None, device=None, requires_grad=False)
float_32_tensor
float_32_tensor.dtype

torch.float32

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 3., 4.], dtype=torch.float16)

In [13]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Multiply it by 10
tensor * 10
tensor

tensor([1, 2, 3])

In [14]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [15]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [16]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])


Operation	                     Calculation	                Code

Element-wise multiplication	     [1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor

Matrix multiplication	            [1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [17]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
# Element-wise matrix multiplication
tensor * tensor
# Matrix multiplication
torch.matmul(tensor, tensor)
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [18]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

# torch.matmul(tensor_A, tensor_B) # (this will error)
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [19]:
# Create a tensor
x = torch.arange(0, 100, 10)
x
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [20]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [21]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [22]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [23]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [24]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


## Indexing (selecting data from tensors)

In [25]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [26]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [27]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensor & Numpy

In [28]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [29]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [30]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.6896, 0.4694, 0.7555, 0.4498],
        [0.3719, 0.1319, 0.9509, 0.3398],
        [0.6952, 0.9227, 0.4064, 0.6372]])

Tensor B:
tensor([[0.2449, 0.0736, 0.1347, 0.7493],
        [0.1386, 0.1948, 0.4412, 0.6325],
        [0.7084, 0.0241, 0.8757, 0.8579]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
import random

# # Set the random seed
RANDOM_SEED=0 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])

Tensor D:
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

'cuda'